### ISSUE TITLE
Internal Server Error upon entering claimed chunk

### ISSUE THREAD

**Issue by WAZUP888** [thexaero/open-parties-and-claims#12]
When entering a claimed chunk, my game gets a Internal Server Error and puts me in a loop that can only be broken by deleting player data. here is the code from the server console. This is the Fabric Version.

09/07/2022 [12:50:30] [Server thread/WARN]: Failed to handle packet for /157.211.151.243:51990
net.minecraft.class_148: Ticking player
    at net.minecraft.class_3222.method_14226(class_3222.java:549) ~[server-intermediary.jar:?]
    at net.minecraft.class_3244.method_18784(class_3244.java:241) ~[server-intermediary.jar:?]
    at net.minecraft.class_2535.method_10754(class_2535.java:246) ~[server-intermediary.jar:?]
    at net.minecraft.class_3242.method_14357(class_3242.java:182) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
    at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/minecraft/class_1074
    at xaero.pac.common.event.CommonEventsFabric.onPlayerTick(CommonEventsFabric.java:131) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at net.minecraft.class_1657.handler$zkl000$onTickHead(class_1657.java:4881) ~[server-intermediary.jar:?]
    at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
    at net.minecraft.class_3222.method_14226(class_3222.java:485) ~[server-intermediary.jar:?]
    ... 9 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1074
    at xaero.pac.common.server.claims.player.ServerPlayerClaimWelcomer.onPlayerTick(ServerPlayerClaimWelcomer.java:73) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?
]
    at xaero.pac.common.server.player.PlayerTickHandler.onTick(PlayerTickHandler.java:51) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at xaero.pac.common.event.CommonEvents.onPlayerTick(CommonEvents.java:140) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at xaero.pac.common.event.CommonEventsFabric.onPlayerTick(CommonEventsFabric.java:129) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at net.minecraft.class_1657.handler$zkl000$onTickHead(class_1657.java:4881) ~[server-intermediary.jar:?]
    at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
    at net.minecraft.class_3222.method_14226(class_3222.java:485) ~[server-intermediary.jar:?]
    ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1074
    at xaero.pac.common.server.claims.player.ServerPlayerClaimWelcomer.onPlayerTick(ServerPlayerClaimWelcomer.java:73) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?
]
    at xaero.pac.common.server.player.PlayerTickHandler.onTick(PlayerTickHandler.java:51) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at xaero.pac.common.event.CommonEvents.onPlayerTick(CommonEvents.java:140) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at xaero.pac.common.event.CommonEventsFabric.onPlayerTick(CommonEventsFabric.java:129) ~[open-parties-and-claims-fabric-1.19-0.4.5.jar:?]
    at net.minecraft.class_1657.handler$zkl000$onTickHead(class_1657.java:4881) ~[server-intermediary.jar:?]
    at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
    at net.minecraft.class_3222.method_14226(class_3222.java:485) ~[server-intermediary.jar:?]
    ... 9 more
09/07/2022 [12:50:30] [Server thread]: WAZUP_888 lost connection: Internal server error
09/07/2022 [12:50:30] [Server thread]: WAZUP_888 left the game

**Comment by thexaero** [comment]
Thanks for reporting!
You don't have to delete any player data, removing the mod would also work. 
I see what the problem is. Going to fix it very soon.
