### ISSUE TITLE
[Ticking Player] - Fabric 1.19.2 - return value is null

### ISSUE THREAD

**Issue by xR4YM0ND** [thexaero/open-parties-and-claims#170]
I updated a bunch of mods and now i can't join my existing singleplayer world

`Caused by: java.lang.NullPointerException: Cannot invoke "xaero.pac.common.parties.party.PartyMemberDynamicInfoSyncable.setPartyId(java.util.UUID)" because the return value of "xaero.pac.common.server.player.data.ServerPlayerData.getPartyMemberDynamicInfo()" is null`

Client [Crash Report](https://gist.github.com/SpigotDE/78913e774251a6ce60e9691ac38ca195)
Client [latest.log](https://gist.github.com/SpigotDE/db633f44b27d5a56036c17cbae2dbeb3)

**Comment by thexaero** [comment]
This is the real cause of the crash, which is not related to my mod:
```
java.lang.NullPointerException: Cannot invoke "draylar.tiered.api.PotentialAttribute.getNbtValues()" because the return value of "java.util.Map.get(Object)" is null
	at draylar.tiered.api.ModifierUtils.removeItemStackAttribute(ModifierUtils.java:140) ~[tiered-1.2.0.jar:?]
	at draylar.tiered.Tiered.updateItemStackNbt(Tiered.java:214) ~[tiered-1.2.0.jar:?]
	at draylar.tiered.Tiered.lambda$onInitialize$2(Tiered.java:103) ~[tiered-1.2.0.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$0(ServerPlayConnectionEvents.java:37) ~[fabric-networking-api-v1-1.2.7+9244241690-2d1738c8afae67fd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.lateInit(ServerPlayNetworkAddon.java:61) ~[fabric-networking-api-v1-1.2.7+9244241690-2d1738c8afae67fd.jar:?]
	at net.minecraft.class_3244.handler$chf001$initAddon(class_3244.java:2556) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.<init>(class_3244.java:255) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:177) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.mdf0958b$lambda$polymer_prePlayHandshakeHackfest$0$0(class_3248.java:2552) ~[client-intermediary.jar:?]
	at eu.pb4.polymer.impl.networking.EarlyConnectionMagic.lambda$handle$0(EarlyConnectionMagic.java:28) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at eu.pb4.polymer.api.x.EarlyPlayNetworkHandler.lambda$onKeepAlive$0(EarlyPlayNetworkHandler.java:98) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$zpo000$redirectExecuteTask(class_1255.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:9777) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
But I did think that I fixed the thing that causes my mod to crash when something like this happens, but I see now that it wasn't perfect. Don't close the issue, because I want to give it another try.

**Comment by thexaero** [comment]
Just so you know, you still need to fix the error that I posted. Even if I fix the crash on my end, the original error will still disconnect you or cause other crashes.

**Comment by xR4YM0ND** [comment]
Globox_Z ( Author of TieredZ ) already knows about that and made a fix i think

I will test this when the update will launch and let you know here
