### ISSUE TITLE
Crashing internal server when NumismaticClaim is present

### ISSUE THREAD

**Issue by xyxt1c** [thexaero/open-parties-and-claims#286]
Since Version b0.17.6-fabric opac crashes xaero's world map when loading a world. _(version b0.17.5-fabric works just fine)_

```
java.lang.NullPointerException: Cannot invoke "xaero.pac.common.server.IServerData.getPlayerPermissionSystemManager()" because "serverData" is null
	at xaero.pac.common.event.CommonEvents.onServerAboutToStart(CommonEvents.java:111)
	at xaero.pac.common.event.CommonEventsFabric.onServerAboutToStart(CommonEventsFabric.java:114)
	at net.minecraft.server.MinecraftServer.handler$gbf000$openpartiesandclaims$onLoadLevel(MinecraftServer.java:9837)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

[crash-2023-06-30_10.39.45-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11914805/crash-2023-06-30_10.39.45-server.txt)

**Comment by thexaero** [comment]
Can you post the crash that you're getting on 0.17.6? This is 0.18.0 and it unintentionally obfuscates the issue.

**Comment by xyxt1c** [comment]
Oh yeah, the b0.17.6 report is much more detailed. Seems to be a **mixin error with NumismaticClaim**.
I tested b0.17.6 and b0.18.0 without NC, both work fine now.

[crash-2023-06-30_12.43.46-server.txt](https://github.com/thexaero/open-parties-and-claims/files/11915693/crash-2023-06-30_12.43.46-server.txt)

**Comment by thexaero** [comment]
Thanks! 
This is an issue on their end. They need to make it compatible with the latest OPAC release.
