### ISSUE TITLE
The server does not shut down properly

### ISSUE THREAD

**Issue by Dr-WeiAL** [thexaero/open-parties-and-claims#289]
I noticed while shutting down the server that it seems that the server is not shutting down properly because of open parties and claims and LuckPerms
```
[02Jul2023 15:43:08.492] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving the game (this may take a moment!)
[02Jul2023 15:43:08.879] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saved the game
[02Jul2023 15:43:10.645] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping the server
[02Jul2023 15:43:10.674] [Server thread/WARN] [environmentalcreepers/]: Invalid entity class name (class not found): 'appeng.entity.SingularityEntity'
[02Jul2023 15:43:10.674] [Server thread/WARN] [environmentalcreepers/]: Invalid explosion class name (class not found): 'slimeknights.tconstruct.gadgets.entity.ExplosionEFLN'
[02Jul2023 15:43:10.788] [Server thread/INFO] [PlasmoVoice/]: UDP server is stopped
[02Jul2023 15:43:10.790] [Server thread/INFO] [PlasmoVoice/]: Addon pv-addon-sculk v1.0.0 by Apehum unloaded
[02Jul2023 15:43:10.792] [Server thread/INFO] [luckperms/]: Starting shutdown process...
[02Jul2023 15:43:10.799] [Server thread/INFO] [luckperms/]: Closing storage...
[02Jul2023 15:43:10.811] [Server thread/INFO] [luckperms/]: Goodbye!
[02Jul2023 15:43:10.813] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[02Jul2023 15:43:10.814] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[02Jul2023 15:43:11.055] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: llbeair lost connection: Disconnected
[02Jul2023 15:43:11.055] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: llbeair[Overworld] left the game
[02Jul2023 15:43:11.055] [Server thread/INFO] [xaero.pac.OpenPartiesAndClaims/]: Updating all forceload tickets for 51b46c95-b24d-3c9d-ac5d-00bb8a91378a
[02Jul2023 15:43:11.056] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: The LuckPerms API isn't loaded yet!
This could be because:
  a) the LuckPerms plugin is not installed or it failed to enable
  b) the plugin in the stacktrace does not declare a dependency on LuckPerms
  c) the plugin in the stacktrace is retrieving the API before the plugin 'enable' phase
     (call the #get method in onEnable, not the constructor!)

	Index: 6
	Listeners:
		0: HIGHEST
		1: ASM: class com.github.ewan_selkirk.dimensionviewer.PlayerListHandler onPlayerDisconnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		2: HIGH
		3: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		4: NORMAL
		5: ASM: class thetadev.constructionwand.basics.CommonEvents logOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		6: ASM: xaero.pac.common.event.CommonEventsForge@9cd18b8 onPlayerLogOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		7: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@4f93ca8a onPlayerLogOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		8: ASM: class top.seraphjack.simplelogin.server.ServerSideEventHandler playerLeave(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		9: ASM: dev.dubhe.curtain.events.utils.ServerEventHandler@3b4337e9 onPlayLoggedOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		10: ASM: dev.dubhe.curtain.events.rules.open_fake_player_inventory.PlayerLoggedEventHandler@4d912c3d onPlayerLeave(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		11: ASM: class dev.xkmc.l2library.base.effects.EffectSyncEvents onServerPlayerLeave(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		12: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		13: ASM: class immersive_paintings.forge.EventBus onPlayerLoggedOutEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$3146/0x00000008016a5758@3f292115
		15: ASM: vazkii.quark.content.tweaks.module.LockRotationModule@2ec17f69 onPlayerLogoff(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		16: ASM: class com.simibubi.create.foundation.events.CommonEvents playerLoggedOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		17: ASM: snownee.kiwi.contributor.Contributors@16982b77 onPlayerLoggedOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		18: net.minecraftforge.eventbus.EventBus$$Lambda$3146/0x00000008016a5758@34320ab2
		19: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@79528550 playerLoggedOut(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		20: ASM: team.creative.playerrevive.server.ReviveEventServer@4627b77d playerLeave(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
		21: ASM: su.plo.voice.server.ModVoiceServer@53886dea onPlayerQuit(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedOutEvent;)V
net.luckperms.api.LuckPermsProvider$NotLoadedException: The LuckPerms API isn't loaded yet!
This could be because:
  a) the LuckPerms plugin is not installed or it failed to enable
  b) the plugin in the stacktrace does not declare a dependency on LuckPerms
  c) the plugin in the stacktrace is retrieving the API before the plugin 'enable' phase
     (call the #get method in onEnable, not the constructor!)

	at TRANSFORMER/luckperms@5.4.66/net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:53)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.player.permission.impl.PlayerLuckPermsSystem.getUser(PlayerLuckPermsSystem.java:103)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.player.permission.impl.PlayerLuckPermsSystem.getCachedMetaData(PlayerLuckPermsSystem.java:118)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.player.permission.impl.PlayerLuckPermsSystem.getIntPermission(PlayerLuckPermsSystem.java:58)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.claims.player.ServerPlayerClaimInfoManager.getPlayerBaseLimit(ServerPlayerClaimInfoManager.java:148)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.claims.ServerClaimsManager.getPlayerBaseForceloadLimit(ServerClaimsManager.java:354)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.claims.forceload.ForceLoadTicketManager.updateTicketsFor(ForceLoadTicketManager.java:131)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.server.player.PlayerLogoutHandler.handle(PlayerLogoutHandler.java:40)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.event.CommonEvents.onPlayerLogOut(CommonEvents.java:175)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.event.CommonEventsForge.onPlayerLogOut(CommonEventsForge.java:120)
	at TRANSFORMER/openpartiesandclaims@0.18.0/xaero.pac.common.event.__CommonEventsForge_onPlayerLogOut_PlayerLoggedOutEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedOut(ForgeEventFactory.java:770)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:331)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1137)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129541_(Connection.java:399)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18709_(BlockableEventLoop.java:88)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9942_(ServerGamePacketListenerImpl.java:354)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_11313_(PlayerList.java:723)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:549)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:521)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)

[02Jul2023 15:43:11.316] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
net.luckperms.api.LuckPermsProvider$NotLoadedException: The LuckPerms API isn't loaded yet!
This could be because:
  a) the LuckPerms plugin is not installed or it failed to enable
  b) the plugin in the stacktrace does not declare a dependency on LuckPerms
  c) the plugin in the stacktrace is retrieving the API before the plugin 'enable' phase
     (call the #get method in onEnable, not the constructor!)

	at net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:53) ~[LuckPerms-Forge-5.4.66.jar%23514!/:5.4.66]
	at xaero.pac.common.server.player.permission.impl.PlayerLuckPermsSystem.getUser(PlayerLuckPermsSystem.java:103) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.server.player.permission.impl.PlayerLuckPermsSystem.getCachedMetaData(PlayerLuckPermsSystem.java:118) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.server.player.permission.impl.PlayerLuckPermsSystem.getIntPermission(PlayerLuckPermsSystem.java:58) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.server.claims.player.ServerPlayerClaimInfoManager.getPlayerBaseLimit(ServerPlayerClaimInfoManager.java:148) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.server.claims.ServerClaimsManager.getPlayerBaseForceloadLimit(ServerClaimsManager.java:354) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.server.claims.forceload.ForceLoadTicketManager.updateTicketsFor(ForceLoadTicketManager.java:131) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.server.player.PlayerLogoutHandler.handle(PlayerLogoutHandler.java:40) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.event.CommonEvents.onPlayerLogOut(CommonEvents.java:175) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.event.CommonEventsForge.onPlayerLogOut(CommonEventsForge.java:120) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at xaero.pac.common.event.__CommonEventsForge_onPlayerLogOut_PlayerLoggedOutEvent.invoke(.dynamic) ~[open-parties-and-claims-forge-1.19.2-0.18.0.jar%23390!/:0.18.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2366!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2366!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2366!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedOut(ForgeEventFactory.java:770) ~[forge-1.19.2-43.2.14-universal.jar%23636!/:?]
	at net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1137) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.network.Connection.m_129541_(Connection.java:399) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18709_(BlockableEventLoop.java:88) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9942_(ServerGamePacketListenerImpl.java:354) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.players.PlayerList.m_11313_(PlayerList.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:549) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:521) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23631!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[02Jul2023 15:43:12.006] [Server thread/INFO] [simplelogin/]: Shutting down player login handler
[02Jul2023 15:43:12.006] [Server thread/INFO] [simplelogin/]: Disabling all plugins
[02Jul2023 15:43:12.007] [Server thread/INFO] [simplelogin/]: Saving all entries
[02Jul2023 15:43:12.008] [Server thread/INFO] [xaero.pac.OpenPartiesAndClaims/]: Stopping IO worker...
[02Jul2023 15:43:12.014] [Server thread/INFO] [xaero.pac.OpenPartiesAndClaims/]: Stopped IO worker!
```

**Comment by thexaero** [comment]
Thanks for reporting!

**Comment by thexaero** [comment]
Yeah, not the best idea for LuckPerms to shut down before players are logged out, but whatever, I'll work around this.

**Comment by Willy1123** [comment]
Hi, I don't know if the problem was fixed, but it's still happening, not with LuckyPerms, but more generally I'd say.

```
[23:43:21] [Server thread/INFO] [co.te.re.Redirector/]: Redirecting io/redspace/ironsspellbooks/api/spells/CastType
[23:43:21] [Server thread/INFO] [voicechat/]: [voicechat] Disconnecting client Zeus1123
[23:43:21] [Server thread/INFO] [xa.pa.OpenPartiesAndClaims/]: Updating all forceload tickets for 926193b0-e85a-4ca6-913a-7f1f26f022dd
[23:43:21] [Server thread/INFO] [co.te.re.Redirector/]: Redirecting com/railwayteam/railways/util/DevCapeUtils
[23:43:23] [Worker-Main-18/INFO] [co.te.re.Redirector/]: Redirecting com/yungnickyoung/minecraft/bettermineshafts/world/generator/pieces/SmallTunnelTurn$TurnDirecti
on
[23:43:23] [Worker-Main-18/INFO] [co.te.re.Redirector/]: Redirecting com/yungnickyoung/minecraft/bettermineshafts/world/generator/pieces/OreDeposit$OreType
[23:43:23] [Worker-Main-12/INFO] [co.te.re.Redirector/]: Redirecting xiroc/dungeoncrawl/dungeon/Tile$Flag
[23:43:37] [Worker-Main-13/INFO] [co.te.re.Redirector/]: Redirecting com/github/alexthe666/iceandfire/world/IafWorldData$FeatureType
[23:43:38] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-196, y=-43, z=-23}
[23:43:39] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-254, y=-1, z=-223}
[23:43:39] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-255, y=-1, z=-223}
[23:43:43] [Worker-Main-10/INFO] [co.te.re.Redirector/]: Redirecting org/violetmoon/zeta/event/bus/ZResult
[23:43:44] [Worker-Main-5/INFO] [co.te.re.Redirector/]: Redirecting yesman/epicfight/world/capabilities/entitypatch/Faction
[23:43:44] [Worker-Main-5/INFO] [co.te.re.Redirector/]: Redirecting yesman/epicfight/data/conditions/entity/HealthPoint$Comparator
[23:43:47] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-129, y=-47, z=81}
[23:43:47] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-131, y=-36, z=-289}
[23:43:47] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-326, y=-34, z=-279}
[23:43:47] [Server thread/ERROR] [minecraft/Util]: POI data mismatch: already registered at BlockPos{x=-55, y=-36, z=69}
save-all
[23:46:25] [Server thread/INFO] [minecraft/MinecraftServer]: Saving the game (this may take a moment!)
[23:46:25] [Server thread/INFO] [minecraft/MinecraftServer]: Saved the game
stop
[23:46:26] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping the server
[23:46:26] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[23:46:26] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[23:46:26] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[23:46:26] [Server thread/INFO] [co.te.re.Redirector/]: Redirecting net/minecraft/world/level/chunk/LevelChunk$EntityCreationType
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/twilightforest:twilight_forest
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/bloodmagic:dungeon
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/mmorpg:dungeon
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/dungeon_realm:dungeon
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/the_harvest:harvest
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/deeperdarker:otherside
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (world): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (harvest): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (otherside): All chunks are saved
[23:46:27] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:46:27] [Server thread/INFO] [Framework/]: Unloading server configs...
[23:46:27] [Server thread/INFO] [Framework/]: Sending config unload event for goblintraders-entities.toml
[23:46:27] [Server thread/INFO] [xa.pa.OpenPartiesAndClaims/]: Stopping IO worker...
[23:46:27] [Server thread/INFO] [xa.pa.OpenPartiesAndClaims/]: Stopped IO worker!
```

**Comment by thexaero** [comment]
@Willy1123 Not sure what you're trying to report. Does it freeze and not fully stop?

**Comment by Willy1123** [comment]
Yep, it freeze and I have to force the server close.

**Comment by thexaero** [comment]
@Willy1123 Please test if it happens without this mod.

**Comment by Willy1123** [comment]
I tested it, and without the open parties and claims mods close it correctly. With the mod it close well sometimes, but the most of the times like 90% it freeze.

**Comment by thexaero** [comment]
@Willy1123 I see, thank you. I'll look into it.
