### ISSUE TITLE
ConcurrentModificationException in PartyManagerFixer

### ISSUE THREAD

**Issue by Martmists-GH** [thexaero/open-parties-and-claims#515]
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1784) ~[?:?] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at xaero.pac.common.server.parties.party.PartyManagerFixer.lambda$fix$1(PartyManagerFixer.java:34) ~[open-parties-and-claims-forge-1.20.1-0.23.0.jar%23472!/:0.23.0] {re:classloading}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at xaero.pac.common.server.parties.party.PartyManagerFixer.fix(PartyManagerFixer.java:33) ~[open-parties-and-claims-forge-1.20.1-0.23.0.jar%23472!/:0.23.0] {re:classloading}
	at xaero.pac.common.server.ServerDataInitializer.init(ServerDataInitializer.java:214) ~[open-parties-and-claims-forge-1.20.1-0.23.0.jar%23472!/:0.23.0] {re:classloading}
	at xaero.pac.common.event.CommonEvents.onServerAboutToStart(CommonEvents.java:110) ~[open-parties-and-claims-forge-1.20.1-0.23.0.jar%23472!/:0.23.0] {re:classloading}
	at xaero.pac.common.event.CommonEventsForge.onServerAboutToStart(CommonEventsForge.java:88) ~[open-parties-and-claims-forge-1.20.1-0.23.0.jar%23472!/:0.23.0] {re:classloading,pl:eventbus:A}
	at xaero.pac.common.event.__CommonEventsForge_onServerAboutToStart_ServerAboutToStartEvent.invoke(.dynamic) ~[open-parties-and-claims-forge-1.20.1-0.23.0.jar%23472!/:0.23.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:98) ~[forge-1.20.1-47.2.0-universal.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:162) ~[server-1.20.1-20230612.114412-srg.jar%23539!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer from mod nochatreports,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23539!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin from mod servercore,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin from mod servercore,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:multiworldborders.mixins.json:MinecraftServerMixin from mod multiworldborders,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin from mod unionlib,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:sandwichable.mixins.json:MinecraftServerMixin from mod sandwichable,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin from mod ichunutil,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23539!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin from mod servercore,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin from mod servercore,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:multiworldborders.mixins.json:MinecraftServerMixin from mod multiworldborders,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin from mod unionlib,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:sandwichable.mixins.json:MinecraftServerMixin from mod sandwichable,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin from mod ichunutil,pl:mixin:A,pl:connector_pre_launch:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
```

**Comment by thexaero** [comment]
Thanks for reporting!

**Comment by thexaero** [comment]
Right, this is actually fixed now.

**Comment by thexaero** [comment]
Oops, not really. Going to be very soon.
