### ISSUE TITLE
NullPointerException - "serverData" is null

### ISSUE THREAD

**Issue by Neoteric-Dev** [thexaero/open-parties-and-claims#592]
java.lang.NullPointerException: Cannot invoke "xaero.pac.common.server.IServerData.getChunkProtection()" because "serverData" is null
	at TRANSFORMER/openpartiesandclaims@0.23.4/xaero.pac.common.event.CommonEvents.onEntityEnteringSection(CommonEvents.java:456)
	at TRANSFORMER/openpartiesandclaims@0.23.4/xaero.pac.common.event.CommonEventsForge.onEntityEnteringSection(CommonEventsForge.java:238)
	at net.minecraftforge.eventbus.ASMEventHandler_120_CommonEventsForge_onEntityEnteringSection_EnteringSection.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.24/net.minecraftforge.common.ForgeHooks.onEntityEnterSection(ForgeHooks.java:1373)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.m_142044_(PersistentEntitySectionManager.java:392)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Entity.m_20343_(Entity.java:2980)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Entity.m_6034_(Entity.java:385)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Entity.m_6478_(Entity.java:590)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2155)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2112)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2544)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Mob.m_8107_(Mob.java:498)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:41)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.raid.Raider.m_8107_(Raider.java:114)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Mob.m_8119_(Mob.java:310)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.mixinextras$bridge$accept$134(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.wrapOperation$bpe000$catchTickingEntities$notTheCauseOfTickLag(Level.java:2575)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_46653_(Level.java:487)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.core.world.storage.VirtualWorld.m_8793_(VirtualWorld.java:106)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.world.data.VirtualWorlds.tickWorld(VirtualWorlds.java:222)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.world.data.VirtualWorlds.tickWorldSafe(VirtualWorlds.java:207)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.world.data.VirtualWorlds.lambda$tick$4(VirtualWorlds.java:142)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.core.world.storage.VirtualWorld.swapThreadsAndRun(VirtualWorld.java:92)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.world.data.VirtualWorlds.lambda$tick$5(VirtualWorlds.java:141)
	at TRANSFORMER/the_vault@1.18.2-3.15.2.3663/iskallia.vault.core.world.threading.ThreadPool.lambda$execute$0(ThreadPool.java:43)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by thexaero** [comment]
Thank you for reporting!
